name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, beta, production]
    
    if: |
      matrix.environment != 'beta' || 
      (matrix.environment == 'beta' && startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-b'))

    steps:
      - name: Checkout code
        uses: actions/checkout@v2