name: Say hi

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Starttoaster/ci-playground/.github/actions/hello@ce6a979b7a10ba343b27cb8eeaf1e6dcf38d2a6d
