name: Say hi

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/hello
