name: CI

on:
  push:
    branches:
      - main
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_name: [dev, beta]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
