name: CI

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_name: [dev, beta]
    env:
      ENV_NAME: ${{ matrix.env_name }}
    if: env.ENV_NAME != 'beta' || (env.ENV_NAME == 'beta' && startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-b')) 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
