name: Set env

on: push

jobs:
  my_job:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Set env
        run: |
          export MY_VAR=$(git log -1 --pretty=%B)
          echo "TESTING_NOTES<<EOF" >> "$GITHUB_ENV"
          echo "$TESTING_NOTES" >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"

      - name: Debug testing notes
        run: |
          echo "$MY_VAR"
          echo "done"