name: Show GitHub Context

on:
  push:
    branches:
      - '**'
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      HELLO: somethingelse
    steps:
      - name: Dump GitHub context
        id: github_context_step
        if: "!contains(env.HELLO, 'orl')"
        run: |
          echo '${{ toJSON(github) }}' > debug.txt
          cat debug.txt
          echo "done"
