name: Greetings

on: push

env:
  WORLD: world

jobs:
  my_job:
    runs-on: ubuntu-latest
    env:
      HELLO_WORLD: "Hello, ${{ env.WORLD }}"
    steps:
      - name: "Say Hello world"
        run: echo "$HELLO_WORLD"
