name: Set env

on: push

jobs:
  my_job:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Set env
        run: |
          export MY_VAR=$(git log -1 --pretty=%B)
          echo "MY_VAR<<EOF" >> "$GITHUB_ENV"
          echo "$MY_VAR" >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"

      - name: Debug testing notes
        run: |
          echo "$MY_VAR"